### ISSUE TITLE
TypeError: gulp.series is not a function

### ISSUE THREAD

**Issue by bantolov** [Rhetos/AdminGui#31]
I am getting this error when running .\Publish.ps1 (after .\Init.ps1).
Should I upgrade some of my tools? How?

```
> adminGui@1.0.0 gulp C:\My Projects\RhetosPackages\AdminGui\AdminGUI
> gulp "default"

C:\My Projects\RhetosPackages\AdminGui\AdminGUI\gulpfile.js:124
gulp.task('default', gulp.series(['build-RxJS-System', 'libs', 'templates', 'appCopy']));
                          ^

TypeError: gulp.series is not a function
    at Object.<anonymous> (C:\My Projects\RhetosPackages\AdminGui\AdminGUI\gulpfile.js:124:27)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (C:\My Projects\RhetosPackages\AdminGui\AdminGUI\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.execute (C:\My Projects\RhetosPackages\AdminGui\AdminGUI\node_modules\liftoff\index.js:203:12)
    at module.exports (C:\My Projects\RhetosPackages\AdminGui\AdminGUI\node_modules\flagged-respawn\index.js:51:3)
    at Liftoff.<anonymous> (C:\My Projects\RhetosPackages\AdminGui\AdminGUI\node_modules\liftoff\index.js:195:5)
    at C:\My Projects\RhetosPackages\AdminGui\AdminGUI\node_modules\liftoff\index.js:165:9
    at C:\My Projects\RhetosPackages\AdminGui\AdminGUI\node_modules\v8flags\index.js:110:14
    at C:\My Projects\RhetosPackages\AdminGui\AdminGUI\node_modules\v8flags\index.js:38:12
    at C:\My Projects\RhetosPackages\AdminGui\AdminGUI\node_modules\v8flags\index.js:49:7
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adminGui@1.0.0 gulp: `gulp "default"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adminGui@1.0.0 gulp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bantolovic\AppData\Roaming\npm-cache\_logs\2018-10-11T13_51_48_395Z-debug.log
```

**Comment by bantolov** [comment]
I noticed that the packages were still generated in folder `AdminGui\PublishOutput` even after the error, and they seem to be working when I deployed them on a demo application.

**Comment by huynguyen-95** [comment]
@bantolov , maybe problem from your environments. I run Publish successfully afer cloning new.
So just try my way like this:
1. If you install **gulp** globally, run ```npm uninstall gulp -g```.
2. Delete **node_modules** in AdminGui folder if it existed.
3. Try to publish again.

**Comment by bantolov** [comment]
Deleting node_modules in AdminGui folder have solved the problem. Thank you!

**Comment by nishatdrupal** [comment]
Getting error on the time of running the command "gulp watch".
gulp version: -3.9.1
node version:-10.16.3
npm version:-6.9.0
" gulp watch
[12:27:07] Using gulpfile C:\xampp\htdocs\car\drupal\web\themes\custom\car\gulpfile.js
[12:27:07] Starting 'watch'…
[12:27:07] 'watch' errored after 4.72 ms
[12:27:07] TypeError: gulp.series is not a function
 at Gulp.<anonymous> (C:\xampp\htdocs\car\drupal\web\themes\custom\car\gulpfile.js:32:41)
 at module.exports (C:\xampp\htdocs\car\drupal\web\themes\custom\car\node_modules\orchestrator\lib\runTask.js:34:7)
 at Gulp.Orchestrator._runTask (C:\xampp\htdocs\car\drupal\web\themes\custom\car\node_modules\orchestrator\index.js:273:3)
 at Gulp.Orchestrator._runStep (C:\xampp\htdocs\car\drupal\web\themes\custom\car\node_modules\orchestrator\index.js:214:10)
 at Gulp.Orchestrator.start (C:\xampp\htdocs\car\drupal\web\themes\custom\car\node_modules\orchestrator\index.js:134:8)
 at C:\Users\nishat\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\versioned\³.7.0\index.js:72:20
 at process._tickCallback (internal/process/next_tick.js:61:11)"

**Comment by nishatdrupal** [comment]
Getting error on the time of running the command "gulp watch".
gulp version: -3.9.1
node version:-10.16.3
npm version:-6.9.0
" gulp watch
[12:27:07] Using gulpfile C:\xampp\htdocs\car\drupal\web\themes\custom\car\gulpfile.js
[12:27:07] Starting 'watch'…
[12:27:07] 'watch' errored after 4.72 ms
**[12:27:07] TypeError: gulp.series is not a function**
 _at Gulp.<anonymous> (C:\xampp\htdocs\car\drupal\web\themes\custom\car\gulpfile.js:32:41)
 at module.exports (C:\xampp\htdocs\car\drupal\web\themes\custom\car\node_modules\orchestrator\lib\runTask.js:34:7)
 at Gulp.Orchestrator._runTask (C:\xampp\htdocs\car\drupal\web\themes\custom\car\node_modules\orchestrator\index.js:273:3)
 at Gulp.Orchestrator._runStep (C:\xampp\htdocs\car\drupal\web\themes\custom\car\node_modules\orchestrator\index.js:214:10)
 at Gulp.Orchestrator.start (C:\xampp\htdocs\car\drupal\web\themes\custom\car\node_modules\orchestrator\index.js:134:8)
 at C:\Users\nishat\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\versioned\³.7.0\index.js:72:20
 at process._tickCallback (internal/process/next_tick.js:61:11)"_

**Comment by huynguyen-95** [comment]
Hi, in **package.json** we are using **gulp** version from 4.0.0 and I noticed that you are using **gulp** version 3.9.1. Could you try to use version 4.0.0 ?
One more thing that we don't have any gulp task named **watch** in gulpfile.js. Do you run it manually?
If you run manually like "gulp watch" it is using your global gulp, try to use "./node_modules/.bin/gulp ..." at AdminGUI folder.
Thanks!

**Comment by PLQin** [comment]
同样遇到了这个问题，解决办法：将 `gulp` 从 `3.9.1` 升级到 `4.0.0`
---
The solution is to upgrade 'gulp' from '3.9.1' to '4.0.0'`

**Comment by s-gaurav** [comment]
How to upgrade Gulp?

**Comment by MihailNenahov** [comment]
I tried setting up gulp 4 (https://www.liquidlight.co.uk/blog/how-do-i-update-to-gulp-4/), but it didn't work for me.

**Comment by w2xi** [comment]
> ## 同样遇到了这个问题，解决办法：将 `gulp` 从 `3.9.1` 升级到 `4.0.0`
> The solution is to upgrade 'gulp' from '3.9.1' to '4.0.0'`

it works, very grateful!
